"use client";

import { useEffect, useState } from "react";
import type { CSSProperties } from "react";
import { fetchJson } from "@/lib/data/client";
import { formatNumber } from "@/lib/format/number";

const MONO = "var(--mono, var(--font-mono))";
const CARD: CSSProperties = { background: "var(--panel)", border: "1px solid var(--border)", borderRadius: "var(--r)", padding: "16px 18px", boxShadow: "var(--sh, var(--shadow))" };
const KICKER: CSSProperties = { fontSize: 11, fontWeight: 600, letterSpacing: ".08em", color: "var(--faint)", marginBottom: 10 };

type Health = {
  generatedAt: string; marketDate: string;
  universe: { size: number | null; source: string; liveIdxRosterDiffReason?: string };
  runLog: Array<{ timestamp: string; marketDate: string; status: string; message: string }>;
  qaSummary?: Record<string, unknown> | null;
  processingSummary?: Record<string, unknown> | null;
  ksei: { snapshots: string[]; latest: string | null; lagNote: string };
  parity: { status: string; method: string; note: string };
  setups: { count: number; scanned: number; quarantined: number; backtest?: Record<string, unknown> };
  manualSpotCheck: { instructions: string; tickers: Array<{ ticker: string; date: string; close: number; volume: number | null; source: string }> };
};

const STATUS_COLOR: Record<string, string> = { SUCCESS: "var(--up)", NO_CHANGE: "var(--muted)", NO_DATA: "var(--warning)", FAILURE: "var(--down)" };

export function DataHealthPage() {
  const [health, setHealth] = useState<Health | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    fetchJson<Health>("/data/data-health.json").then(setHealth).catch(() => setError("data-health.json is not published yet — it is generated by the daily pipeline."));
  }, []);

  if (error) return <section style={{ maxWidth: 1320, margin: "0 auto" }}><div style={{ ...CARD, color: "var(--muted)", fontSize: 13 }}>{error}</div></section>;
  if (!health) return <section style={{ maxWidth: 1320, margin: "0 auto" }}><div style={{ ...CARD, color: "var(--muted)", fontSize: 13 }}>Loading…</div></section>;

  return (
    <section style={{ maxWidth: 1320, margin: "0 auto" }}>
      <div style={{ marginBottom: 18 }}>
        <h1 style={{ margin: "0 0 6px", fontSize: 24, fontWeight: 700, letterSpacing: "-.01em" }}>Data Health</h1>
        <p style={{ margin: 0, color: "var(--muted)", fontSize: 13.5 }}>
          Run report for <b style={{ fontFamily: MONO, color: "var(--text)" }}>{health.marketDate}</b> · generated {health.generatedAt?.slice(0, 16).replace("T", " ")} WIB
        </p>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(300px,1fr))", gap: 14, marginBottom: 14 }}>
        <div style={CARD}>
          <div style={KICKER}>UNIVERSE</div>
          <div style={{ fontFamily: MONO, fontSize: 26, fontWeight: 700 }}>{health.universe.size === null ? "—" : formatNumber(health.universe.size, 0)}</div>
          <div style={{ fontSize: 11.5, color: "var(--muted)", marginTop: 4 }}>{health.universe.source}</div>
          {health.universe.liveIdxRosterDiffReason ? <div style={{ fontSize: 10.5, color: "var(--warning)", marginTop: 8 }}>⚠ Live IDX roster diff: {health.universe.liveIdxRosterDiffReason}</div> : null}
        </div>
        <div style={CARD}>
          <div style={KICKER}>TRADINGVIEW PARITY</div>
          <div style={{ fontFamily: MONO, fontSize: 15, fontWeight: 700, color: health.parity.status === "UNVERIFIED" ? "var(--warning)" : "var(--up)" }}>{health.parity.status}</div>
          <div style={{ fontSize: 11.5, color: "var(--muted)", marginTop: 6, lineHeight: 1.5 }}>{health.parity.method}</div>
          <div style={{ fontSize: 10.5, color: "var(--faint)", marginTop: 6 }}>{health.parity.note}</div>
        </div>
        <div style={CARD}>
          <div style={KICKER}>SWING ENGINE</div>
          <div style={{ display: "flex", gap: 8 }}>
            {([["Setups", health.setups.count], ["Scanned", health.setups.scanned], ["Quarantined", health.setups.quarantined]] as const).map(([l, v]) => (
              <div key={l} style={{ flex: 1, background: "var(--soft)", borderRadius: 9, padding: "9px 6px", textAlign: "center" }}>
                <div style={{ fontFamily: MONO, fontSize: 18, fontWeight: 700 }}>{formatNumber(v, 0)}</div>
                <div style={{ fontSize: 9.5, color: "var(--muted)" }}>{l}</div>
              </div>
            ))}
          </div>
          {health.setups.backtest ? <div style={{ fontSize: 10.5, color: "var(--muted)", marginTop: 8, lineHeight: 1.5 }}>Backtest sanity: {String(health.setups.backtest["signals"])} signals · hit-rate (decided) {String(health.setups.backtest["hitRateDecided"])} · {String(health.setups.backtest["undecidedIn5Bars"])} undecided in 5 bars.</div> : null}
        </div>
        <div style={CARD}>
          <div style={KICKER}>KSEI SNAPSHOTS</div>
          <div style={{ fontFamily: MONO, fontSize: 13, fontWeight: 600 }}>{health.ksei.snapshots.join(" · ") || "—"}</div>
          <div style={{ fontSize: 10.5, color: "var(--warning)", marginTop: 8 }}>{health.ksei.lagNote}</div>
        </div>
      </div>

      <div style={{ ...CARD, marginBottom: 14 }}>
        <div style={KICKER}>RUN LOG · LAST {health.runLog.length}</div>
        {health.runLog.slice().reverse().map((e, i) => (
          <div key={i} style={{ display: "flex", gap: 10, alignItems: "baseline", padding: "6px 0", borderTop: i ? "1px solid var(--hair)" : "none", fontSize: 12 }}>
            <span style={{ fontFamily: MONO, fontSize: 10.5, color: "var(--faint)", width: 130, flexShrink: 0 }}>{e.timestamp?.slice(0, 16).replace("T", " ")}</span>
            <span style={{ fontFamily: MONO, fontWeight: 700, fontSize: 10.5, color: STATUS_COLOR[e.status] || "var(--muted)", width: 78, flexShrink: 0 }}>{e.status}</span>
            <span style={{ color: "var(--muted)" }}>{e.message}</span>
          </div>
        ))}
      </div>

      <div style={CARD}>
        <div style={KICKER}>MANUAL TRADINGVIEW SPOT-CHECK</div>
        <p style={{ margin: "0 0 10px", fontSize: 12, color: "var(--muted)" }}>{health.manualSpotCheck.instructions}</p>
        <div style={{ overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>
            <thead><tr>{["Ticker", "Date", "Close (site)", "Volume (site)", "Source", "TradingView"].map((h) => <th key={h} style={{ textAlign: "left", padding: "6px 10px 6px 0", color: "var(--faint)", fontSize: 10, letterSpacing: ".06em", borderBottom: "1px solid var(--hair)" }}>{h.toUpperCase()}</th>)}</tr></thead>
            <tbody>
              {health.manualSpotCheck.tickers.map((t) => (
                <tr key={t.ticker}>
                  <td style={{ fontFamily: MONO, fontWeight: 700, padding: "7px 10px 7px 0", borderBottom: "1px solid var(--hair)" }}>{t.ticker}</td>
                  <td style={{ fontFamily: MONO, padding: "7px 10px 7px 0", borderBottom: "1px solid var(--hair)", color: "var(--muted)" }}>{t.date}</td>
                  <td style={{ fontFamily: MONO, padding: "7px 10px 7px 0", borderBottom: "1px solid var(--hair)" }}>{formatNumber(t.close, 0)}</td>
                  <td style={{ fontFamily: MONO, padding: "7px 10px 7px 0", borderBottom: "1px solid var(--hair)" }}>{t.volume === null ? "—" : formatNumber(t.volume, 0)}</td>
                  <td style={{ padding: "7px 10px 7px 0", borderBottom: "1px solid var(--hair)", color: "var(--muted)" }}>{t.source}</td>
                  <td style={{ padding: "7px 0", borderBottom: "1px solid var(--hair)" }}><a href={`https://www.tradingview.com/chart/?symbol=IDX%3A${t.ticker}`} target="_blank" rel="noreferrer" style={{ color: "var(--accent)", fontWeight: 600, textDecoration: "none" }}>open ↗</a></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}
